#!/usr/bin/env bash
set -euo pipefail

# v3c 셀프호스팅 빌드 스크립트 (v2 문법 사용)
# src/v3_hosted/*.b 파일들을 합쳐서 v3c_full로 컴파일

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_dir="$(cd "$script_dir/.." && pwd)"
out_dir="$root_dir/build"
v3h_src="$root_dir/src/v3_hosted"
lib_src="$root_dir/src/library/v2"

V3C="$root_dir/bin/v3c_full"

merged="$out_dir/v3c_merged_v2.b"
out_asm="$out_dir/v3c_selfhost.asm"

echo "=== v3c Self-hosting Build (v2 syntax) ==="

# 모든 소스 파일 합치기 (import 순서대로)
cat > "$merged" << 'HEADER'
// v3c Self-hosted compiler (merged source - v2 syntax)
// Generated by build_selfhost_v2.sh
HEADER

# 1. 표준 라이브러리 먼저 (v2)
lib_files=(
    "$lib_src/io.b"
    "$lib_src/mem.b"
    "$lib_src/str.b"
    "$lib_src/vec.b"
    "$lib_src/hashmap.b"
    "$lib_src/panic.b"
    "$lib_src/arena.b"
    "$lib_src/string_builder.b"
)

for f in "${lib_files[@]}"; do
    if [[ -f "$f" ]]; then
        echo "// === $(basename $f) ===" >> "$merged"
        # import 문과 alias 문 제거
        grep -v "^import \|alias [a-z]* :" "$f" >> "$merged" || true
        echo "" >> "$merged"
    else
        echo "Warning: $f not found"
    fi
done

# 2. v3_hosted 컴파일러 모듈
v3h_files=(
    "$v3h_src/token.b"
    "$v3h_src/ast.b"
    "$v3h_src/lexer.b"
    "$v3h_src/ir.b"
    "$v3h_src/parser.b"
    "$v3h_src/lowering.b"
    "$v3h_src/typecheck.b"
    "$v3h_src/codegen.b"
)

for f in "${v3h_files[@]}"; do
    if [[ -f "$f" ]]; then
        echo "// === $(basename $f) ===" >> "$merged"
        grep -v "^import " "$f" >> "$merged" || true
        echo "" >> "$merged"
    else
        echo "Warning: $f not found"
    fi
done

# 3. 드라이버 (main)
drv="$v3h_src/driver.b"
if [[ -f "$drv" ]]; then
    echo "// === driver.b ===" >> "$merged"
    grep -v "^import " "$drv" >> "$merged" || true
fi

echo "✓ Merged source: $merged ($(wc -l < "$merged") lines)"

# 4. v3c로 컴파일
echo "Compiling with v3c_full..."
if "$V3C" "$merged" > "$out_asm" 2>&1; then
    echo "✓ Compiled: $out_asm ($(wc -l < "$out_asm") lines)"
else
    echo "✗ Compilation failed:"
    head -50 "$out_asm"
    exit 1
fi

# 5. 어셈블 및 링크
echo "Assembling and linking..."
nasm -f elf64 -o "$out_dir/v3c_selfhost.o" "$out_asm"
ld -o "$out_dir/v3c_gen1" "$out_dir/v3c_selfhost.o"

echo "✓ Built: $out_dir/v3c_gen1"
ls -lh "$out_dir/v3c_gen1"

# 6. 간단한 테스트
echo ""
echo "=== Testing v3c_gen1 ==="
echo 'func main() { return 42; }' > "$out_dir/test42.b"
if "$out_dir/v3c_gen1" "$out_dir/test42.b" > "$out_dir/test42.asm" 2>&1; then
    echo "✓ v3c_gen1 can compile simple file"
    nasm -f elf64 -o "$out_dir/test42.o" "$out_dir/test42.asm"
    ld -o "$out_dir/test42" "$out_dir/test42.o"
    "$out_dir/test42" || true
    echo "Exit code: $?"
else
    echo "✗ Test failed:"
    cat "$out_dir/test42.asm"
fi

echo ""
echo "=== Self-hosting build complete ==="
