#!/usr/bin/env bash
set -euo pipefail

# v3c 셀프호스팅 빌드 스크립트
# bpp/src/*.bpp 파일들을 v3 문법으로 컴파일

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_dir="$(cd "$script_dir/.." && pwd)"
out_dir="$root_dir/build"
bpp_src="$root_dir/bpp/src"
std_src="$bpp_src/std"

# v3c_full 컴파일러 (v2c로 빌드된 전체 파이프라인)
V3C="$root_dir/bin/v3c_full"

# 출력 파일
merged="$out_dir/v3c_merged.bpp"
out_asm="$out_dir/v3c_selfhost.asm"

echo "=== v3c Self-hosting Build ==="

# 1. 모든 소스 파일 합치기 (import 순서대로)
cat > "$merged" << 'HEADER'
// v3c Self-hosted compiler (merged source)
// Generated by build_selfhost.sh
HEADER

# 표준 라이브러리 먼저
for f in "$std_src"/{io,mem,file,vec,hashmap,panic,str,arena,conv}.bpp; do
    if [[ -f "$f" ]]; then
        echo "// === $(basename $f) ===" >> "$merged"
        # import 문 제거하고 추가
        grep -v "^import " "$f" >> "$merged" || true
        echo "" >> "$merged"
    fi
done

# 컴파일러 모듈
for f in "$bpp_src"/{token,ast,lexer,parser,ir,lowering,typecheck,codegen,driver}.bpp; do
    if [[ -f "$f" ]]; then
        echo "// === $(basename $f) ===" >> "$merged"
        grep -v "^import " "$f" >> "$merged" || true
        echo "" >> "$merged"
    fi
done

# 메인 파일 (마지막)
echo "// === main.bpp ===" >> "$merged"
grep -v "^import " "$bpp_src/main.bpp" >> "$merged" || true

echo "✓ Merged source: $merged ($(wc -l < "$merged") lines)"

# 2. v3c로 컴파일
echo "Compiling with v3c_full..."
if "$V3C" "$merged" > "$out_asm" 2>&1; then
    echo "✓ Compiled: $out_asm ($(wc -l < "$out_asm") lines)"
else
    echo "✗ Compilation failed:"
    head -50 "$out_asm"
    exit 1
fi

# 3. 어셈블 및 링크
echo "Assembling and linking..."
nasm -f elf64 -o "$out_dir/v3c_selfhost.o" "$out_asm"
ld -o "$out_dir/v3c_gen1" "$out_dir/v3c_selfhost.o"

echo "✓ Built: $out_dir/v3c_gen1"
ls -lh "$out_dir/v3c_gen1"

# 4. 간단한 테스트
echo ""
echo "=== Testing v3c_gen1 ==="
echo 'func main() { return 42; }' > "$out_dir/test42.bpp"
if "$out_dir/v3c_gen1" "$out_dir/test42.bpp" > "$out_dir/test42.asm" 2>&1; then
    echo "✓ v3c_gen1 can compile simple file"
    nasm -f elf64 -o "$out_dir/test42.o" "$out_dir/test42.asm"
    ld -o "$out_dir/test42" "$out_dir/test42.o"
    "$out_dir/test42" && echo "Exit code: $?" || echo "Exit code: $?"
else
    echo "✗ Test failed:"
    cat "$out_dir/test42.asm"
fi

echo ""
echo "=== Self-hosting build complete ==="
