#!/usr/bin/env bash
set -euo pipefail

# v3c 셀프호스팅 빌드 스크립트
# bpp/src/*.bpp 파일들을 v3 문법으로 컴파일

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_dir="$(cd "$script_dir/.." && pwd)"
out_dir="$root_dir/build"
bpp_src="$root_dir/bpp/src"
std_src="$bpp_src/std"

# v3c_full 컴파일러 (v2c로 빌드된 전체 파이프라인)
# 주의: bpp 파일들이 아직 v2 문법이므로 v2c를 사용
V3C="$root_dir/bin/v2c"

# 출력 파일
merged="$out_dir/v3c_merged.bpp"
out_asm="$out_dir/v3c_selfhost.asm"

echo "=== v3c Self-hosting Build ==="
echo "[DEBUG] Script started at $(date '+%H:%M:%S')"

# 1. 모든 소스 파일 합치기 (import 순서대로)
echo "[DEBUG] Step 1: Merging source files..."
cat > "$merged" << 'HEADER'
// v3c Self-hosted compiler (merged source)
// Generated by build_selfhost.sh
HEADER

# 표준 라이브러리 먼저
echo "[DEBUG] Merging std lib files..."
echo "[DEBUG] std_src = $std_src"
file_count=0
for f in "$std_src"/{io,mem,file,vec,hashmap,panic,str,arena,conv}.bpp; do
    if [[ -f "$f" ]]; then
        echo "[DEBUG]   - $(basename $f) ($(wc -l < "$f") lines)"
        echo "[DEBUG]     Processing: $f"
        echo "// === $(basename $f) ===" >> "$merged"
        # sed를 사용해 import 제거 (grep과 달리 항상 성공)
        echo "[DEBUG]     Running sed..."
        sed '/^import /d' "$f" >> "$merged"
        echo "[DEBUG]     sed completed"
        echo "" >> "$merged"
        echo "[DEBUG]     echo blank line completed"
        file_count=$((file_count + 1))
        echo "[DEBUG]     file_count = $file_count"
    else
        echo "[DEBUG]   - $(basename $f) NOT FOUND"
    fi
done
echo "[DEBUG] Merged $file_count std lib files"

# 컴파일러 모듈
echo "[DEBUG] Merging compiler modules..."
file_count=0
for f in "$bpp_src"/{token,ast,lexer,parser,ir,lowering,typecheck,codegen,driver}.bpp; do
    if [[ -f "$f" ]]; then
        echo "[DEBUG]   - $(basename $f) ($(wc -l < "$f") lines)"
        echo "// === $(basename $f) ===" >> "$merged"
        # sed를 사용해 import 제거 (grep과 달리 항상 성공)
        sed '/^import /d' "$f" >> "$merged"
        echo "" >> "$merged"
        file_count=$((file_count + 1))
    else
        echo "[DEBUG]   - $(basename $f) NOT FOUND"
    fi
done
echo "[DEBUG] Merged $file_count compiler modules"

# 메인 파일 (마지막)
echo "[DEBUG] Merging main.bpp..."
if [[ -f "$bpp_src/main.bpp" ]]; then
    echo "// === main.bpp ===" >> "$merged"
    sed '/^import /d' "$bpp_src/main.bpp" >> "$merged"
    echo "[DEBUG]   - main.bpp ($(wc -l < "$bpp_src/main.bpp") lines)"
else
    echo "[DEBUG]   - main.bpp NOT FOUND"
fi

merged_lines=$(wc -l < "$merged")
echo "✓ Merged source: $merged ($merged_lines lines)"
echo "[DEBUG] Merge completed at $(date '+%H:%M:%S')"

# 1.5. enum을 const로 변환 (v2c 호환성)
echo "[DEBUG] Step 1.5: Converting enums to consts..."
python3 "$script_dir/convert_enum_to_const.py" < "$merged" > "$merged.tmp"
mv "$merged.tmp" "$merged"
converted_lines=$(wc -l < "$merged")
echo "✓ Converted enums to consts ($converted_lines lines)"

# 2. v3c로 컴파일
echo ""
echo "[DEBUG] Step 2: Compiling merged source..."
echo "[DEBUG] Input: $merged ($merged_lines lines)"
echo "[DEBUG] Compiler: $V3C"
echo "[DEBUG] Compilation started at $(date '+%H:%M:%S')"
echo "[DEBUG] Running with 300s timeout..."

# 타임아웃과 함께 실행 (무한루프 방지) - 300초 = 5분
if timeout 300s "$V3C" "$merged" > "$out_asm" 2>&1; then
    asm_lines=$(wc -l < "$out_asm")
    echo "[DEBUG] Compilation completed at $(date '+%H:%M:%S')"
    echo "✓ Compiled: $out_asm ($asm_lines lines)"
else
    exit_code=$?
    if [ $exit_code -eq 124 ]; then
        echo "[ERROR] Compilation TIMEOUT (>30s) - likely infinite loop!"
    else
        echo "[ERROR] Compilation failed with exit code: $exit_code"
    fi
    echo "✗ Compilation failed:"
    head -50 "$out_asm"
    exit 1
fi

# 3. 어셈블 및 링크
echo ""
echo "[DEBUG] Step 3: Assembling and linking..."
echo "[DEBUG] Assemble started at $(date '+%H:%M:%S')"
nasm -f elf64 -o "$out_dir/v3c_selfhost.o" "$out_asm"
echo "[DEBUG] Link started at $(date '+%H:%M:%S')"
ld -o "$out_dir/v3c_gen1" "$out_dir/v3c_selfhost.o"
echo "[DEBUG] Link completed at $(date '+%H:%M:%S')"

echo "✓ Built: $out_dir/v3c_gen1"
ls -lh "$out_dir/v3c_gen1"

# 4. 간단한 테스트
echo ""
echo "=== Testing v3c_gen1 ==="
echo "[DEBUG] Test started at $(date '+%H:%M:%S')"
echo 'func main() { return 42; }' > "$out_dir/test42.bpp"
echo "[DEBUG] Running v3c_gen1 with 10s timeout..."
if timeout 10s "$out_dir/v3c_gen1" "$out_dir/test42.bpp" > "$out_dir/test42.asm" 2>&1; then
    echo "[DEBUG] v3c_gen1 compilation succeeded"
    echo "✓ v3c_gen1 can compile simple file"
    nasm -f elf64 -o "$out_dir/test42.o" "$out_dir/test42.asm"
    ld -o "$out_dir/test42" "$out_dir/test42.o"
    "$out_dir/test42" && result=$? || result=$?
    echo "Exit code: $result"
    if [ $result -eq 42 ]; then
        echo "[DEBUG] ✓ Test PASSED (exit code 42)"
    else
        echo "[DEBUG] ✗ Test FAILED (expected 42, got $result)"
    fi
else
    exit_code=$?
    if [ $exit_code -eq 124 ]; then
        echo "[ERROR] v3c_gen1 TIMEOUT (>10s) - likely infinite loop!"
    else
        echo "[ERROR] v3c_gen1 failed with exit code: $exit_code"
    fi
    echo "✗ Test failed:"
    cat "$out_dir/test42.asm"
fi

echo ""
echo "[DEBUG] Build completed at $(date '+%H:%M:%S')"
echo "=== Self-hosting build complete ==="
